// packages/react/src/components/Button/Button.tsx
import React from "react";
import { colors } from "@pabbii/tokens";

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: "primary" | "secondary";
}

export const Button = ({
  variant = "primary",
  style,
  ...props
}: ButtonProps) => {
  const backgroundColor =
    variant === "primary" ? colors.primary : colors.secondary;

  return (
    <button
      style={{
        backgroundColor,
        color: colors.white,
        padding: "8px 16px",
        borderRadius: "4px",
        border: "none",
        cursor: "pointer",
        ...style,
      }}
      {...props}
    />
  );
};

Button.displayName = "Button";

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import { computed } from 'vue';
import { colors } from '@pabbii/tokens';

interface Props {
  variant?: 'primary' | 'secondary';
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
});

const backgroundColor = computed(() => 
  props.variant === 'primary' ? colors.primary : colors.secondary
);
</script>

<template>
  <button
    :style="{
      backgroundColor,
      color: colors.white,
      padding: '8px 16px',
      borderRadius: '4px',
      border: 'none',
      cursor: 'pointer',
    }"
    v-bind="$attrs"
  >
    <slot />
  </button>
</template>
